name: Lint diagnostics

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - run: npm ci --silent
      - run: npm run lint
